//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cybiosphere.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ENTITY_FORMVIEW             101
#define IDD_BIOCTRL_FORMVIEW            102
#define IDD_BRAIN_FORMVIEW              103
#define IDD_GENETIC_FORMVIEW            104
#define IDD_STATISTIC_FORMVIEW          105
#define IDD_LOGSERVER_FORMVIEW          106
#define IDR_MAINFRAME                   128
#define IDR_BIOTOP_TYPE                 129
#define IDB_VEGET                       131
#define IDB_ANIM                        132
#define IDR_ENTITY_TYPE                 134
#define IDR_BIOCTRL_TYPE                135
#define IDR_BRAIN_TYPE                  136
#define IDR_GENETIC_TYPE                137
#define IDB_GENOME_ICONS                144
#define IDD_DLG_GENOME_EDITOR           150
#define IDD_DLG_ENTITY_CREATOR          151
#define IDI_ICON_SAVE                   155
#define IDI_ICON_OPEN                   156
#define IDD_DLG_BRAIN_EDITOR            157
#define IDB_SEX_ICONS                   159
#define IDB_FORM_ICONS                  160
#define IDI_ICON_LESS                   163
#define IDI_ICON_MORE                   164
#define IDR_STATISTIC_TYPE              165
#define IDB_BITMAP1                     166
#define IDB_MINERAL                     167
#define IDB_BITMAP2                     168
#define IDB_ODOR_ICONS                  169
#define IDD_DLG_                        172
#define IDD_DLG_ENTITY_EDITOR           172
#define IDB_PHEROMON_ICONS              174
#define IDB_TASTE_ICONS                 175
#define IDD_DLG_BIOTOP_EDITOR           177
#define IDD_DLG_MEASURE_EDITOR          178
#define IDD_DLG_ENTITY_FIND             179
#define IDD_MAP_FORMVIEW                180
#define IDB_ANIM1                       181
#define IDB_ANIM2                       182
#define IDB_ANIM3                       183
#define IDB_ANIM4                       184
#define IDB_ANIM5                       185
#define IDB_ANIM6                       186
#define IDB_ANIM0                       188
#define IDB_TEXTURE_ICONS               189
#define IDB_ATTRIBUTE_ICONS             191
#define IDB_TEMPER_COLOR                194
#define IDB_HEALTH_ICONS                196
#define IDB_LOGO                        199
#define IDD_DIALOG_TRAIN                202
#define IDP_FAILED_OPEN_DATABASE        203
#define IDR_MAPCONFIG_TYPE              210
#define IDR_LOGSERVER_TYPE              211
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_BUTTON1                     1003
#define IDC_BUTTON_AUTO                 1003
#define IDC_EDIT4                       1003
#define IDC_BUTTON_ACCEPT               1003
#define IDC_BUTTON_SCENARIO             1003
#define IDC_BUTTON_EXPORT               1003
#define IDC_BUTTON2                     1004
#define IDC_PROGRESS1                   1004
#define IDC_BUTTON_STICK                1004
#define IDC_BUTTON_IMPORT               1004
#define IDC_CHECK1                      1005
#define IDC_BUTTON_CARROT               1005
#define IDC_CHECK2                      1006
#define IDC_CHECK3                      1007
#define IDC_CHECK4                      1008
#define IDC_CHECK5                      1009
#define IDC_BUTTON_EXEC                 1012
#define IDC_FEEDBACK                    1013
#define IDC_CUR_ACTION                  1014
#define IDC_EDIT_SEX                    1015
#define IDC_FEEL_PREV                   1015
#define IDC_BUTTON_PRED                 1016
#define IDC_BUTTON_GRID                 1017
#define IDC_EDIT_CHOICE                 1018
#define IDC_BUTTON_EDIT                 1018
#define IDC_FEEL_CUR                    1019
#define IDC_BUTTON3                     1020
#define IDC_FEEL_DIF                    1020
#define IDC_LEARNING                    1021
#define IDC_SLIDER_ZOOM                 1022
#define IDC_BUTTON_EDIT_IDENTIFY        1022
#define IDC_SLIDER_SPEED                1023
#define IDC_DATA1                       1023
#define IDC_DATA2                       1024
#define IDC_TREE1                       1025
#define IDC_DATA3                       1026
#define IDC_EDIT                        1027
#define IDC_DATA4                       1029
#define IDC_LABEL1                      1030
#define IDC_LABEL2                      1031
#define IDC_LABEL3                      1032
#define IDC_COMBO_CLASS                 1032
#define IDC_ENTITY_NAME                 1033
#define IDC_DATA5                       1033
#define IDC_RADIO1                      1034
#define IDC_LABEL4                      1035
#define IDC_RADIO2                      1035
#define IDC_RADIO3                      1036
#define IDC_BUTTON_CREATE               1037
#define IDC_RADIO4                      1037
#define IDC_RADIO_NONE                  1037
#define IDC_TREE_GENOME                 1038
#define IDC_RADIO5                      1038
#define IDC_SPECIE_NAME                 1039
#define IDC_RADIO_ODOR6                 1039
#define IDC_EDIT_CX                     1040
#define IDC_RADIO_ODOR7                 1040
#define IDC_EDIT_CY                     1041
#define IDC_BUTTON_ADD                  1042
#define IDC_COMBO1                      1043
#define IDC_COMBO2                      1044
#define IDC_SLIDER_M1                   1045
#define IDC_SLIDER_M2                   1046
#define IDC_SLIDER_M3                   1047
#define IDC_SLIDER_M4                   1048
#define IDC_SLIDER_P1                   1049
#define IDC_SLIDER_P2                   1050
#define IDC_SLIDER_P3                   1051
#define IDC_SLIDER_P4                   1052
#define IDC_EDIT_SLIDEM1                1053
#define IDC_EDIT_SLIDEM2                1054
#define IDC_EDIT_SLIDEM3                1055
#define IDC_EDIT_SLIDEM4                1056
#define IDC_EDIT_DESCM                  1057
#define IDC_EDIT_SLIDEP1                1058
#define IDC_EDIT_SLIDEP2                1059
#define IDC_EDIT_SLIDEP3                1060
#define IDC_EDIT_SLIDEP4                1061
#define IDC_EDIT_DESCP                  1062
#define IDC_EDIT_LAYER                  1063
#define IDC_COMBO3                      1063
#define IDC_BUTTON_SAVE                 1064
#define IDC_BUTTON_LOAD                 1065
#define IDC_BRAIN_GRID                  1065
#define IDC_BRAIN_EDIT_GRID             1066
#define IDC_COMBO4                      1066
#define IDC_BUTTON_MORE                 1067
#define IDC_COMBO5                      1067
#define IDC_BUTTON_LESS                 1068
#define IDC_SET_BRAIN                   1069
#define IDC_EDIT_MUTE_RATE              1070
#define IDC_LIST_WEIGHT_M               1071
#define IDC_LIST_WEIGHT_P               1072
#define IDC_EDIT_TIMER                  1075
#define IDC_CHECK_IMMORTAL              1076
#define IDC_EDIT_SCENARIO               1076
#define IDC_EDIT_AGE                    1077
#define IDC_RADIO_AUTO                  1078
#define IDC_RADIO_STICK                 1079
#define IDC_RADIO_CARROT                1080
#define IDC_EDIT_LABEL                  1081
#define IDC_LIST_MEASURES               1086
#define IDC_EDIT_NAME                   1087
#define IDC_COMBO_TYPE                  1088
#define IDC_EDIT_TITLE1                 1089
#define IDC_EDIT_TITLE2                 1090
#define IDC_EDIT_TITLE3                 1091
#define IDC_EDIT_TITLE4                 1092
#define IDC_EDIT_TITLE5                 1093
#define IDC_EDIT_PERIOD                 1094
#define IDC_COMBO_SUBTYPE               1095
#define IDC_COMBO_ENTITY                1096
#define IDC_LIST_ENTITY                 1096
#define IDC_COMBO_REACTION              1097
#define IDC_RADIO_ODOR1                 1097
#define IDC_COMBO_SPECIE                1098
#define IDC_RADIO_ODOR2                 1098
#define IDC_COMBO_EVENT                 1099
#define IDC_RADIO_ODOR3                 1099
#define IDC_EDIT_THRESHOLD              1100
#define IDC_RADIO_ODOR4                 1100
#define IDC_RADIO_ODOR5                 1101
#define IDC_EDIT_BIOTOP                 1102
#define IDC_RADIO_PURPOSE1              1102
#define IDC_RADIO_PURPOSE2              1103
#define IDC_EDIT_BIOTOP2                1103
#define IDC_RADIO_PURPOSE3              1104
#define IDC_RADIO_PURPOSE4              1105
#define IDC_RADIO_PURPOSE5              1106
#define IDC_RADIO_PURPOSE6              1107
#define IDC_RADIO_PURPOSE7              1108
#define IDC_PURPOSE_TXT1                1109
#define IDC_PURPOSE_TXT2                1110
#define IDC_COMBO_WIND                  1110
#define IDC_PURPOSE_TXT3                1111
#define IDC_EDIT_LOG                    1111
#define IDC_PURPOSE_TXT4                1112
#define IDC_PURPOSE_TXT5                1113
#define IDC_PURPOSE_TXT6                1114
#define IDC_PHYS_WELFARE                1114
#define IDC_PURPOSE_TXT7                1115
#define IDC_FEELING_WELFARE             1115
#define IDC_SENSOR_TXT1                 1116
#define IDC_SENSOR_TXT2                 1117
#define IDC_SENSOR_TXT3                 1118
#define IDC_SENSOR_TXT4                 1119
#define IDC_RADIO_SENSOR1               1120
#define IDC_RADIO_SENSOR2               1121
#define IDC_RADIO_SENSOR3               1122
#define IDC_RADIO_PURPOSE11             1123
#define IDC_RADIO_SENSOR4               1123
#define IDC_RADIO_POPULATION1           1124
#define IDC_POPULATION_TXT1             1125
#define IDC_RADIO_POPULATION2           1126
#define IDC_RADIO_POPULATION3           1127
#define IDC_RADIO_POPULATION4           1128
#define IDC_POPULATION_TXT2             1129
#define IDC_POPULATION_TXT3             1130
#define IDC_POPULATION_TXT4             1131
#define IDC_RADIO_POPULATION5           1132
#define IDC_RADIO_POPULATION6           1133
#define IDC_POPULATION_TXT5             1134
#define IDC_POPULATION_TXT6             1135
#define IDC_SLIDER1                     1136
#define IDC_POPULATION_DATE             1137
#define IDC_DELTA_CHECK1                1137
#define IDC_DELTA_CHECK2                1138
#define IDC_FILTER_STRING               1140
#define ID_APP_DISPLAY_GENETIC          32771
#define ID_APP_DISPLAY_BRAIN            32772
#define ID_GENOME_EDIT                  32773
#define ID_PAIR_EDIT                    32774
#define ID_PAIR_ADD                     32775
#define ID_PAIR_REMOVE                  32776
#define ID_APP_ADD_NEW_ENTITY           32779
#define ID_APP_REMOVE_ENTITY            32780
#define ID_APP_EDIT_GENOME              32781
#define ID_APP_EDIT_BRAIN               32782
#define ID_APP_DISPLAY_STAT             32783
#define ID_APP_SELECT_VIEW              32784
#define ID_APP_SELECT_STICK             32785
#define ID_APP_SELECT_CARROT            32786
#define ID_APP_SELECT_CREATE            32787
#define ID_APP_DISPLAY_3D               32788
#define ID_APP_DISPLAY_2D               32789
#define ID_APP_DISPLAY_MAP              32790
#define ID_FILE_NEW_BIOTOP              32791
#define ID_FILE_OPEN_BIOTOP             32792
#define ID_FILE_SAVE_BIOTOP             32793
#define ID_FILE_SAVE_AS_BIOTOP          32794
#define ID_BUTTON32800                  32800
#define ID_APP_MONITOR_SHORT            32801
#define ID_APP_MONITOR_LONG             32802
#define ID_APP_VIEW_LOG                 32803
#define ID_APP_ADD_GROUP_ENTITY         32804
#define ID_FILE_RUN_SCENARIO_BIOTOP     32805
#define ID_APP_EDIT_TRAIN_AND_GRADE     32807
#define ID_APP_EDIT_IDENTIFY            32808
#define ID_APP_EDIT_CHECK_IDENTIFY      32809
#define ID_APP_DISPLAY_LOGSERVER        32810
#define ID_APP_MONITOR_SPECIE           32811
#define ID_APP_DISPLAY_2DSAT            32812
#define ID_EDIT_MONITORSPECIEBIOMASS    32812
#define ID_APP_MONITOR_BIOMASS          32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
